version: '3.8'

services:
  ollama:
    image: ollama/ollama:0.6.3
    container_name: ollama
    restart: unless-stopped
    expose:
      - 11434
    volumes:
      - ../data/models:/root/.ollama

  reader:
    build:
      context:
        .
    ports:
      - "8080:8080"